/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package net.ausiasmarch.neptuno.gui;

import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.ausiasmarch.common.Convert;
import net.ausiasmarch.neptuno.dao.EmpleadoDAO;
import net.ausiasmarch.neptuno.dao.OficinaDAO;
import net.ausiasmarch.neptuno.entity.Empleado;
import net.ausiasmarch.neptuno.model.Operation;

/**
 *
 * @author a048598270y
 */
public class MantEmpleados extends JDialog {

    private static long id;
    private static Operation op;
    private EmpleadoDAO empleadoDAO;
    private OficinaDAO oficinaDAO;
    
    /**
     * Creates new form MantEmpleados
     */
    public MantEmpleados(java.awt.Frame parent, boolean modal, long id, Operation op) {
        super(parent, modal);
        this.id = id;
        initComponents();
        jTextFieldId.setText(String.valueOf(id));
        
        empleadoDAO = new EmpleadoDAO();
        oficinaDAO = new OficinaDAO();
        
        switch (op) {
            case NEW:
                pantallaCrear();
                break;
            case EDIT:
                pantallaEditar();
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldApellidos = new javax.swing.JTextField();
        jTextFieldNaci = new javax.swing.JTextField();
        jTextFieldAlta = new javax.swing.JTextField();
        jComboBoxIdOficina = new javax.swing.JComboBox();
        jComboBoxCargo = new javax.swing.JComboBox();
        jButtonAceptar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("DejaVu Sans", 0, 24)); // NOI18N
        jLabelTitulo.setText("Nuevo empleado");

        jLabel3.setText("IdOficina");

        jLabel5.setText("Id del empleado:");

        jTextFieldId.setEnabled(false);

        jLabel6.setText("Nombre");

        jLabel7.setText("Cargo");

        jLabel8.setText("Fecha de nacimiento");

        jLabel9.setText("Fecha de alta");

        jLabel10.setText("Apellidos");

        jComboBoxIdOficina.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccionar--" }));

        jComboBoxCargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Seleccionar--" }));

        jButtonAceptar.setBackground(new java.awt.Color(51, 255, 102));
        jButtonAceptar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAceptar.setText("Crear");
        jButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceptarActionPerformed(evt);
            }
        });

        jButtonCancelar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonCancelar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxIdOficina, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 93, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(jTextFieldNaci, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                                    .addComponent(jTextFieldNombre))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel7)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldAlta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldAlta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldNaci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxIdOficina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAceptar)
                    .addComponent(jButtonCancelar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(this, "¿Seguro que desea cancelar?", "Cancelar operacion", JOptionPane.OK_CANCEL_OPTION) == 0) {
            dispose();
        }
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceptarActionPerformed
        if (!validarDatos()) {
            return;  
        }
        String nombre    = jTextFieldNombre.getText();
        String apellidos = jTextFieldApellidos.getText();
        int cargo        = Convert.parseInt(jComboBoxCargo.getSelectedItem().toString());
        Long oficina     = Convert.parseLong(jComboBoxIdOficina.getSelectedItem().toString());
        Date fechaNaci   = Convert.parseDate(jTextFieldNaci.getText());
        Date fechaAlta   = Convert.parseDate(jTextFieldAlta.getText());
        String ciudad = oficinaDAO.findById(oficina).getCiudad();
        int oficinaint = Convert.parseInt(jComboBoxIdOficina.getSelectedItem().toString());
        
        java.sql.Date sqlNaci = new java.sql.Date(fechaNaci.getTime());
        java.sql.Date sqlAlta = new java.sql.Date(fechaAlta.getTime());
        
        Empleado e = new Empleado(id, nombre, apellidos, cargo, oficinaint, sqlNaci, sqlAlta);
        
        empleadoDAO.create(e);
    }//GEN-LAST:event_jButtonAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MantEmpleados dialog = new MantEmpleados(new javax.swing.JFrame(), true, id, op);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private boolean validarDatos() {
        
        if (jTextFieldNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo nombre esta vacío");
            return false;
        }
        if(jTextFieldApellidos.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "El campo apellidos esta vacío");
            return false; 
        }
        if (jTextFieldNaci.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo fecha de nacimiento esta vacío");
            return false;
        }
        if (jTextFieldAlta.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "El campo fecha de alta esta vacío");
            return false;
        }
        if(!Convert.isValidDate(jTextFieldNaci.getText())){
            JOptionPane.showMessageDialog(null, "El campo fecha de nacimiento no es valido");
            return false; 
        }
        if(!Convert.isValidDate(jTextFieldAlta.getText())){
            JOptionPane.showMessageDialog(null, "El campo fecha de alta no es valido");
            return false; 
        }
        
        return true;
    }
    
    private void pantallaCrear() {
        jLabelTitulo.setText("Nuevo empleado");
        jButtonAceptar.setText("Crear");
        llenarComboBox();
    }
    
    private void pantallaEditar() {
        Empleado empleado;
        
        jLabelTitulo.setText("Editar empleado");
        jButtonAceptar.setText("Editar");
        
        empleado = empleadoDAO.findById(id);
        
        jTextFieldNombre.setText(empleado.getNombre());
        jTextFieldApellidos.setText(empleado.getApellidos());
        jTextFieldNaci.setText(empleado.getNaci().toString());
        jTextFieldAlta.setText(empleado.getAlta().toString());
        
        llenarComboBox();
        
        jComboBoxCargo.setSelectedItem(empleado.getCargo());
        jComboBoxIdOficina.setSelectedItem(empleado.getIdOficina());
    }
    
    private void llenarComboBox() {

        List<String> listaCargo = empleadoDAO.cargo();

        for (int i = 0; i < listaCargo.size(); i++) {
            jComboBoxCargo.addItem(listaCargo.get(i));
        }

        List<Integer> listaOfi = empleadoDAO.idOficina();

        for (int i = 0; i < listaOfi.size(); i++) {
            jComboBoxIdOficina.addItem(listaOfi.get(i));
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceptar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JComboBox jComboBoxCargo;
    private javax.swing.JComboBox jComboBoxIdOficina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldAlta;
    private javax.swing.JTextField jTextFieldApellidos;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNaci;
    private javax.swing.JTextField jTextFieldNombre;
    // End of variables declaration//GEN-END:variables
}
